"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.StakeOpen__factory = exports.BaseStakingV2__factory = exports.token = exports.remote = exports.library = exports.interfaces = exports.initiators = exports.factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.factory = __importStar(require("./factory"));
exports.initiators = __importStar(require("./initiators"));
exports.interfaces = __importStar(require("./interfaces"));
exports.library = __importStar(require("./library"));
exports.remote = __importStar(require("./remote"));
exports.token = __importStar(require("./token"));
var BaseStakingV2__factory_1 = require("./BaseStakingV2__factory");
Object.defineProperty(exports, "BaseStakingV2__factory", { enumerable: true, get: function () { return BaseStakingV2__factory_1.BaseStakingV2__factory; } });
var StakeOpen__factory_1 = require("./StakeOpen__factory");
Object.defineProperty(exports, "StakeOpen__factory", { enumerable: true, get: function () { return StakeOpen__factory_1.StakeOpen__factory; } });
