"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.StakeOpenUpgradeable__factory = exports.QuantumPortalStakeWithDelegateUpgradeable__factory = exports.OperatorRelationUpgradeable__factory = exports.IQuantumPortalStakeWithDelegate__factory = exports.IOperatorRelation__factory = exports.BaseStakingV2Upgradeable__factory = exports.library = exports.interfaces = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.interfaces = __importStar(require("./interfaces"));
exports.library = __importStar(require("./library"));
var BaseStakingV2Upgradeable__factory_1 = require("./BaseStakingV2Upgradeable__factory");
Object.defineProperty(exports, "BaseStakingV2Upgradeable__factory", { enumerable: true, get: function () { return BaseStakingV2Upgradeable__factory_1.BaseStakingV2Upgradeable__factory; } });
var IOperatorRelation__factory_1 = require("./IOperatorRelation__factory");
Object.defineProperty(exports, "IOperatorRelation__factory", { enumerable: true, get: function () { return IOperatorRelation__factory_1.IOperatorRelation__factory; } });
var IQuantumPortalStakeWithDelegate__factory_1 = require("./IQuantumPortalStakeWithDelegate__factory");
Object.defineProperty(exports, "IQuantumPortalStakeWithDelegate__factory", { enumerable: true, get: function () { return IQuantumPortalStakeWithDelegate__factory_1.IQuantumPortalStakeWithDelegate__factory; } });
var OperatorRelationUpgradeable__factory_1 = require("./OperatorRelationUpgradeable__factory");
Object.defineProperty(exports, "OperatorRelationUpgradeable__factory", { enumerable: true, get: function () { return OperatorRelationUpgradeable__factory_1.OperatorRelationUpgradeable__factory; } });
var QuantumPortalStakeWithDelegateUpgradeable__factory_1 = require("./QuantumPortalStakeWithDelegateUpgradeable__factory");
Object.defineProperty(exports, "QuantumPortalStakeWithDelegateUpgradeable__factory", { enumerable: true, get: function () { return QuantumPortalStakeWithDelegateUpgradeable__factory_1.QuantumPortalStakeWithDelegateUpgradeable__factory; } });
var StakeOpenUpgradeable__factory_1 = require("./StakeOpenUpgradeable__factory");
Object.defineProperty(exports, "StakeOpenUpgradeable__factory", { enumerable: true, get: function () { return StakeOpenUpgradeable__factory_1.StakeOpenUpgradeable__factory; } });
