"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IOperatorRelation__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "nodeOperator",
                type: "address",
            },
        ],
        name: "getDelegateForOperator",
        outputs: [
            {
                components: [
                    {
                        internalType: "address",
                        name: "delegate",
                        type: "address",
                    },
                    {
                        internalType: "uint8",
                        name: "deleted",
                        type: "uint8",
                    },
                ],
                internalType: "struct IOperatorRelation.Relationship",
                name: "",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class IOperatorRelation__factory {
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IOperatorRelation__factory = IOperatorRelation__factory;
IOperatorRelation__factory.abi = _abi;
