/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dummyErc20Sol from "./DummyErc20.sol";
export type { dummyErc20Sol };
import type * as examples from "./examples";
export type { examples };
export type { DummyUpgradedToken } from "./DummyUpgradedToken";
