"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.WalletRegistration__factory = exports.TokenFactory__factory = exports.QpErc20Token__factory = exports.IWalletRegistration__factory = exports.ITokenFactory__factory = exports.IFeeStore__factory = exports.IBitcoinIntent__factory = exports.FeeStore__factory = exports.Bitcoin__factory = exports.BatchCall__factory = exports.utils = exports.test = exports.enganglement = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.enganglement = __importStar(require("./enganglement"));
exports.test = __importStar(require("./test"));
exports.utils = __importStar(require("./utils"));
var BatchCall__factory_1 = require("./BatchCall__factory");
Object.defineProperty(exports, "BatchCall__factory", { enumerable: true, get: function () { return BatchCall__factory_1.BatchCall__factory; } });
var Bitcoin__factory_1 = require("./Bitcoin__factory");
Object.defineProperty(exports, "Bitcoin__factory", { enumerable: true, get: function () { return Bitcoin__factory_1.Bitcoin__factory; } });
var FeeStore__factory_1 = require("./FeeStore__factory");
Object.defineProperty(exports, "FeeStore__factory", { enumerable: true, get: function () { return FeeStore__factory_1.FeeStore__factory; } });
var IBitcoinIntent__factory_1 = require("./IBitcoinIntent__factory");
Object.defineProperty(exports, "IBitcoinIntent__factory", { enumerable: true, get: function () { return IBitcoinIntent__factory_1.IBitcoinIntent__factory; } });
var IFeeStore__factory_1 = require("./IFeeStore__factory");
Object.defineProperty(exports, "IFeeStore__factory", { enumerable: true, get: function () { return IFeeStore__factory_1.IFeeStore__factory; } });
var ITokenFactory__factory_1 = require("./ITokenFactory__factory");
Object.defineProperty(exports, "ITokenFactory__factory", { enumerable: true, get: function () { return ITokenFactory__factory_1.ITokenFactory__factory; } });
var IWalletRegistration__factory_1 = require("./IWalletRegistration__factory");
Object.defineProperty(exports, "IWalletRegistration__factory", { enumerable: true, get: function () { return IWalletRegistration__factory_1.IWalletRegistration__factory; } });
var QpErc20Token__factory_1 = require("./QpErc20Token__factory");
Object.defineProperty(exports, "QpErc20Token__factory", { enumerable: true, get: function () { return QpErc20Token__factory_1.QpErc20Token__factory; } });
var TokenFactory__factory_1 = require("./TokenFactory__factory");
Object.defineProperty(exports, "TokenFactory__factory", { enumerable: true, get: function () { return TokenFactory__factory_1.TokenFactory__factory; } });
var WalletRegistration__factory_1 = require("./WalletRegistration__factory");
Object.defineProperty(exports, "WalletRegistration__factory", { enumerable: true, get: function () { return WalletRegistration__factory_1.WalletRegistration__factory; } });
