/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IQuantumPortalLedgerMgr__factory } from "./IQuantumPortalLedgerMgr__factory";
export { IQuantumPortalLedgerMgrDependencies__factory } from "./IQuantumPortalLedgerMgrDependencies__factory";
