"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QpMultiSender__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var QpMultiSender__factory_1 = require("./QpMultiSender__factory");
Object.defineProperty(exports, "QpMultiSender__factory", { enumerable: true, get: function () { return QpMultiSender__factory_1.QpMultiSender__factory; } });
