"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.QuantumPortalWorkPoolServerUpgradeable__factory = exports.QuantumPortalWorkPoolClientUpgradeable__factory = exports.QuantumPortalMinerMgrUpgradeable__factory = exports.QuantumPortalMinerMembershipUpgradeable__factory = exports.QuantumPortalFeeConverterUpgradeable__factory = exports.QuantumPortalFeeConverterDirectUpgradeable__factory = exports.QuantumPortalAuthorityMgrUpgradeable__factory = exports.IQuantumPortalWorkPoolServer__factory = exports.IQuantumPortalWorkPoolClient__factory = exports.IQuantumPortalMinerMgr__factory = exports.IQuantumPortalMinerMembership__factory = exports.IQuantumPortalFinalizerPrecompile__factory = exports.IQuantumPortalFeeConvertor__factory = exports.IQuantumPortalAuthorityMgr__factory = exports.IDelegator__factory = exports.DelegatorUpgradeable__factory = exports.stake = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.stake = __importStar(require("./stake"));
var DelegatorUpgradeable__factory_1 = require("./DelegatorUpgradeable__factory");
Object.defineProperty(exports, "DelegatorUpgradeable__factory", { enumerable: true, get: function () { return DelegatorUpgradeable__factory_1.DelegatorUpgradeable__factory; } });
var IDelegator__factory_1 = require("./IDelegator__factory");
Object.defineProperty(exports, "IDelegator__factory", { enumerable: true, get: function () { return IDelegator__factory_1.IDelegator__factory; } });
var IQuantumPortalAuthorityMgr__factory_1 = require("./IQuantumPortalAuthorityMgr__factory");
Object.defineProperty(exports, "IQuantumPortalAuthorityMgr__factory", { enumerable: true, get: function () { return IQuantumPortalAuthorityMgr__factory_1.IQuantumPortalAuthorityMgr__factory; } });
var IQuantumPortalFeeConvertor__factory_1 = require("./IQuantumPortalFeeConvertor__factory");
Object.defineProperty(exports, "IQuantumPortalFeeConvertor__factory", { enumerable: true, get: function () { return IQuantumPortalFeeConvertor__factory_1.IQuantumPortalFeeConvertor__factory; } });
var IQuantumPortalFinalizerPrecompile__factory_1 = require("./IQuantumPortalFinalizerPrecompile__factory");
Object.defineProperty(exports, "IQuantumPortalFinalizerPrecompile__factory", { enumerable: true, get: function () { return IQuantumPortalFinalizerPrecompile__factory_1.IQuantumPortalFinalizerPrecompile__factory; } });
var IQuantumPortalMinerMembership__factory_1 = require("./IQuantumPortalMinerMembership__factory");
Object.defineProperty(exports, "IQuantumPortalMinerMembership__factory", { enumerable: true, get: function () { return IQuantumPortalMinerMembership__factory_1.IQuantumPortalMinerMembership__factory; } });
var IQuantumPortalMinerMgr__factory_1 = require("./IQuantumPortalMinerMgr__factory");
Object.defineProperty(exports, "IQuantumPortalMinerMgr__factory", { enumerable: true, get: function () { return IQuantumPortalMinerMgr__factory_1.IQuantumPortalMinerMgr__factory; } });
var IQuantumPortalWorkPoolClient__factory_1 = require("./IQuantumPortalWorkPoolClient__factory");
Object.defineProperty(exports, "IQuantumPortalWorkPoolClient__factory", { enumerable: true, get: function () { return IQuantumPortalWorkPoolClient__factory_1.IQuantumPortalWorkPoolClient__factory; } });
var IQuantumPortalWorkPoolServer__factory_1 = require("./IQuantumPortalWorkPoolServer__factory");
Object.defineProperty(exports, "IQuantumPortalWorkPoolServer__factory", { enumerable: true, get: function () { return IQuantumPortalWorkPoolServer__factory_1.IQuantumPortalWorkPoolServer__factory; } });
var QuantumPortalAuthorityMgrUpgradeable__factory_1 = require("./QuantumPortalAuthorityMgrUpgradeable__factory");
Object.defineProperty(exports, "QuantumPortalAuthorityMgrUpgradeable__factory", { enumerable: true, get: function () { return QuantumPortalAuthorityMgrUpgradeable__factory_1.QuantumPortalAuthorityMgrUpgradeable__factory; } });
var QuantumPortalFeeConverterDirectUpgradeable__factory_1 = require("./QuantumPortalFeeConverterDirectUpgradeable__factory");
Object.defineProperty(exports, "QuantumPortalFeeConverterDirectUpgradeable__factory", { enumerable: true, get: function () { return QuantumPortalFeeConverterDirectUpgradeable__factory_1.QuantumPortalFeeConverterDirectUpgradeable__factory; } });
var QuantumPortalFeeConverterUpgradeable__factory_1 = require("./QuantumPortalFeeConverterUpgradeable__factory");
Object.defineProperty(exports, "QuantumPortalFeeConverterUpgradeable__factory", { enumerable: true, get: function () { return QuantumPortalFeeConverterUpgradeable__factory_1.QuantumPortalFeeConverterUpgradeable__factory; } });
var QuantumPortalMinerMembershipUpgradeable__factory_1 = require("./QuantumPortalMinerMembershipUpgradeable__factory");
Object.defineProperty(exports, "QuantumPortalMinerMembershipUpgradeable__factory", { enumerable: true, get: function () { return QuantumPortalMinerMembershipUpgradeable__factory_1.QuantumPortalMinerMembershipUpgradeable__factory; } });
var QuantumPortalMinerMgrUpgradeable__factory_1 = require("./QuantumPortalMinerMgrUpgradeable__factory");
Object.defineProperty(exports, "QuantumPortalMinerMgrUpgradeable__factory", { enumerable: true, get: function () { return QuantumPortalMinerMgrUpgradeable__factory_1.QuantumPortalMinerMgrUpgradeable__factory; } });
var QuantumPortalWorkPoolClientUpgradeable__factory_1 = require("./QuantumPortalWorkPoolClientUpgradeable__factory");
Object.defineProperty(exports, "QuantumPortalWorkPoolClientUpgradeable__factory", { enumerable: true, get: function () { return QuantumPortalWorkPoolClientUpgradeable__factory_1.QuantumPortalWorkPoolClientUpgradeable__factory; } });
var QuantumPortalWorkPoolServerUpgradeable__factory_1 = require("./QuantumPortalWorkPoolServerUpgradeable__factory");
Object.defineProperty(exports, "QuantumPortalWorkPoolServerUpgradeable__factory", { enumerable: true, get: function () { return QuantumPortalWorkPoolServerUpgradeable__factory_1.QuantumPortalWorkPoolServerUpgradeable__factory; } });
