/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as library from "./library";
export type { library };
export type { BaseStakingV2Upgradeable } from "./BaseStakingV2Upgradeable";
export type { StakeOpenUpgradeable } from "./StakeOpenUpgradeable";
