"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DummyERC20__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var DummyERC20__factory_1 = require("./DummyERC20__factory");
Object.defineProperty(exports, "DummyERC20__factory", { enumerable: true, get: function () { return DummyERC20__factory_1.DummyERC20__factory; } });
