"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UniswapOracle__factory = exports.IPriceOracle__factory = exports.IFrmFeeManager__factory = exports.FrmFeeManager__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var FrmFeeManager__factory_1 = require("./FrmFeeManager__factory");
Object.defineProperty(exports, "FrmFeeManager__factory", { enumerable: true, get: function () { return FrmFeeManager__factory_1.FrmFeeManager__factory; } });
var IFrmFeeManager__factory_1 = require("./IFrmFeeManager__factory");
Object.defineProperty(exports, "IFrmFeeManager__factory", { enumerable: true, get: function () { return IFrmFeeManager__factory_1.IFrmFeeManager__factory; } });
var IPriceOracle__factory_1 = require("./IPriceOracle__factory");
Object.defineProperty(exports, "IPriceOracle__factory", { enumerable: true, get: function () { return IPriceOracle__factory_1.IPriceOracle__factory; } });
var UniswapOracle__factory_1 = require("./UniswapOracle__factory");
Object.defineProperty(exports, "UniswapOracle__factory", { enumerable: true, get: function () { return UniswapOracle__factory_1.UniswapOracle__factory; } });
